name: Auto Update Playlist

on:
  schedule:
    - cron: '0 */1 * * *'  # Every 3 hours
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Install Python dependencies
      run: pip install requests

    - name: Create fld
      run: mkdir tmp_script

    - name: Unp
      env:
        FILE_API: ${{ secrets.FILE_APIS }}
      run: |
        unzip -o -P "$FILE_API" dld.zip -d tmp_script

    - name: Rps
      run: python3 tmp_script/dld.py

    - name: DARS
      if: always()
      run: rm -rf tmp_script

    - name: Clone target Repo
      run: |
        git clone https://x-access-token:${{ secrets.TARGET_TOKEN2TS }}@${{ secrets.TARGET_URLTS }} ${{ secrets.TARGET_NAMETS }}

    - name: Copy target repo
      run: |
        cp *.m3u ${{ secrets.TARGET_NAMETS }}/*.m3u

    - name: Commit & push to target repository
      run: |
        cd ${{ secrets.TARGET_NAMETS }}
        git config user.name "${{ secrets.TARGET_REPO_USER }}"
        git config user.email "${{ secrets.TARGET_REPO_USER }}@users.noreply.github.com"
        git add *.m3u
        git commit -m " Auto update HilayTV playlist on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
